spring.application.name=sistema-xingu-ia
groq.api.url=groq.api.url=https://api.groq.com/openai/v1/chat/completions

spring.datasource.url=jdbc:mysql://localhost:3306/sax_bd
spring.datasource.username=root
spring.datasource.password=*Gui1709*06
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver